### ISSUE TITLE
ERROR DOMException: Failed to execute 'querySelector' on 'Document': '#37473550'

### ISSUE THREAD

**Issue by michaeltre** [MarcinMichalik/ng-scrollTo#12]
I very liked the simplicity of this library but for some reason, I've got an error when trying to reach Document object. Do you have any ideas why it happens?

```
ERROR DOMException: Failed to execute 'querySelector' on 'Document': '#37473550' is not a valid selector.
    at ScrollToService.webpackJsonp../node_modules/ng2-scroll-to-el/scrollTo.service.js.ScrollToService.scrollTo (https://something.com/vendor.bundle.js:106147:31)
    at SafeSubscriber._next (https://something.com/main.bundle.js:7818:63)
    at SafeSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub (https://something.com/vendor.bundle.js:119143:16)
    at SafeSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.SafeSubscriber.next (https://something.com/vendor.bundle.js:119090:22)
    at Subscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber._next (https://something.com/vendor.bundle.js:119031:26)
    at Subscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.next (https://something.com/vendor.bundle.js:118995:18)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/operators/map.js.MapSubscriber._next (https://something.com/vendor.bundle.js:123216:26)
    at MapSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.next (https://something.com/vendor.bundle.js:118995:18)
    at FilterSubscriber.webpackJsonp../node_modules/rxjs/_esm5/operators/filter.js.FilterSubscriber._next (https://something.com/vendor.bundle.js:122765:30)
    at FilterSubscriber.webpackJsonp../node_modules/rxjs/_esm5/Subscriber.js.Subscriber.next (https://something.com/vendor.bundle.js:118995:18)
```

Inside the component I'm calling to the service like this:
``` 
this.itemSKU = this.utilsService.getQueryParams()['sku'];

if (this.itemSKU) {
  this.scrollToService.scrollTo('#' + this.itemSKU);
}
```

**Comment by michaeltre** [comment]
After functionality was moved under ngAfterViewInit everything works fine.

**Comment by michaeltre** [comment]
Sorry for reopening the issue, but it still exists.
```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '51913135' is not a valid selector.
    at eval (eval at webpackJsonp../node_modules/ng2-scroll-to-el/scrollTo.service.js.ScrollToService.scrollTo (https://something.com/vendor.bundle.js:106147:22), <anonymous>:1:10)
```
I debbuged it and find that the problem happens inside the library in line 11 of scrollTo.service.js:
```
        if (typeof element === 'string') {
            var el = document.querySelector(element);
```
For some reason on that stage document object falls with the querySelector. I've tried the same query with getElementById on this stage and it works.
